wandb:
  project: studentcup_2022
  exp_num: 1
  tags: [bert]
path:
  train_file_name: /workspace/studentcup_2022/data/train.csv
  test_file_name: /workspace/studentcup_2022/data/test.csv
  checkpoint_path: checkpoints
model:
  n_classes: 4
  max_token_len: 512
  n_linears: 1
  d_hidden_linear: 128
  dropout_rate: 0.3
  pooling_type: cls
  #pooling_type: cls_meanpooled
  #pooling_type: max
  #pooling_type: 4_cls
  added_feature_num: 0
training:
  n_epochs: 10
  batch_size: 16
  learning_rate: 0.01
  pl_seed: 0
  n_gpus: 1
  test_size: 0.2
  #fold: kf
  #fold: skf
callbacks:
  patience: 5
  patience_min_delta: 0